### ISSUE TITLE
Announcement quality for Electrostar & Turbostar

### ISSUE THREAD

**Issue by real-geko7844** [davwheat/rail-announcements#105]
Hi David, I've just discovered the Rail Announcement site and I'm enjoying playing around with it. It's packed with some great features and you've done an excellent job at keeping it accessible and user friendly. 

I have noticed that some of the announcement quality with the Electrostar/Turbostar Julie Berry is poor and I think you mention that this is because they're recorded (e.g. Preston Park). Some stations also sound strange - almost like it's a Julie impersonator - East Croydon being an example (but it's probably just the pitching). Whilst I don't have any recordings to improve the quality, I have a possible suggestion. 

Is the 'station glossary' for Julie on the Electrostar the same on the Class 700? They certainly sound the same to me, although I'm not all that familiar with trains and haven't been on an Electrostar for some time. Clearly the 700 has a different style of announcements, however the actual station name recordings sound the same. If this is true, would it make sense to use the Class 700 'station glossary' recordings but format the announcements so they continue to be in the Electrostar style? (As a side note, Balcome is also missing from the Electrostar glossary - poor unloved Balcome). 

Unfortunately, I don't have the technical know-how to even consider trying to do this myself, which is why I've raised it as an "issue". If I started trying to mess around with the file names, your website would be down before you can say qwerty, and no one wants that. 

As I say, please keep up the good work with the website; it's interesting to reminisce about when I commuted on a no-longer-existing train time. Cheers! G

**Comment by davwheat** [comment]
Amusingly, the ones you call a Julie impersonator are very likely to be the ones copied from the Class 700!

The 377/387/etc only have one recording per station, but the 700 has a high/low version depending on where it is in a list, meaning they sound out of place on the Electrostar system.

The better option would be to get out with some better recording equipment and roam around on Southern trains, but sadly I don't have the hardware for that (nor the patience!).

**Comment by 313rail** [comment]
I have some better recordings for Preston park and Hove if you want them

**Comment by davwheat** [comment]
Yes, please. I just need to remember to actually add them though!

**Comment by 313rail** [comment]
[Uploading files.zip…]()

**Comment by 313rail** [comment]
[files.zip](https://github.com/davwheat/rail-announcements/files/13923253/files.zip)

**Comment by 313rail** [comment]
PRP.mp3 and HOV.mp3

**Comment by real-geko7844** [comment]
> Amusingly, the ones you call a Julie impersonator are very likely to be the ones copied from the Class 700!
> 
> The 377/387/etc only have one recording per station, but the 700 has a high/low version depending on where it is in a list, meaning they sound out of place on the Electrostar system.
> 
> The better option would be to get out with some better recording equipment and roam around on Southern trains, but sadly I don't have the hardware for that (nor the patience!).

Hi David, Thanks for your response. That is rather amusing; clearly I don't know my trains very well. I was just thinking if that would serve as a simple fix for you, but naturally, it's something you've already considered. Unfortunately, I don't have the time, patience (or indeed the finances, now that a return ticket to Brighton costs about the same as an all inclusive family holiday to the Maldives) to record any new stations. It's a shame, as I rather enjoy the soothing tone of Julie Berry's voice!

**Comment by davwheat** [comment]
I'll leave this open so I remember to add the PRP and HOV recordings
