### ISSUE TITLE
Announcement tabs have been swapped

### ISSUE THREAD

**Issue by GTRspotter** [davwheat/rail-announcements#108]
Announcement tabs have been swapped

**Comment by davwheat** [comment]
I literally have no idea what this even means

**Comment by GTRspotter** [comment]
![image](https://github.com/davwheat/rail-announcements/assets/140901151/9ccd1607-15f9-4856-b23e-9c57881abc09)

**Comment by GTRspotter** [comment]
![image](https://github.com/davwheat/rail-announcements/assets/140901151/d700345b-d12b-4c33-9082-9454ea40d501)
