### ISSUE TITLE
Eurostar announcements do not play using Live Trains

### ISSUE THREAD

**Issue by Boalbads** [davwheat/rail-announcements#111]
While I am aware that Eurostar trains are announced differently at STP (seen here: https://www.youtube.com/watch?v=ESoW0ngJ9rY), it would be nice for them to be more than just on the PIS (or maybe a separate page for Eurostar announcements under celia?) The hardest thing I can think of is probably the French translation, or perhaps sourcing the words "Paris" etc.

**Comment by davwheat** [comment]
The trains are in the data, so this would be much easier than expected at first glance.

It would simply be mapping the stations to the right audio files (they're currently not).

**Comment by davwheat** [comment]
Basic Eurostar announcements should work on the site now.

The audio released by KeTech doesn't include the custom Eurostar audio files, such as "departure to" and "is now ready for boarding", so it's not possible to do proper style announcements for the services.

https://github.com/davwheat/rail-announcements/assets/7406822/c96da67b-54d8-4938-9262-ab396b31e1ac

**Comment by Boalbads** [comment]
Don't know if its intentional maybe, but you are unable to use Paris or the others in regular announcements,
![image](https://github.com/davwheat/rail-announcements/assets/68003904/24bad3c6-917d-45fa-b147-096261805fb1)
![image](https://github.com/davwheat/rail-announcements/assets/68003904/86c52c54-1d88-40cb-89f5-24003357a208)

**Comment by davwheat** [comment]
The announcements will work in the normal announcement generator if you choose the thing with unknown name. It's just because the station isn't in my database as it's not in the UK.

**Comment by Boalbads** [comment]
Ah okay, thanks!

**Comment by Boalbads** [comment]
they cant be used in intermediate stops but i presume thats intended
![image](https://github.com/davwheat/rail-announcements/assets/68003904/d5f451a7-9243-4e91-a0e1-422d983b97d2)

**Comment by davwheat** [comment]
A quirk of how the intermediate stations work I think. That's fixable so thanks for letting me know

**Comment by Boalbads** [comment]
if you have a bit of time, i found a _few_ more stations you might wanna add for eurostar:
AVI - Avignon
MSC - marsaille
MCK - disnyland
ROT - Rotterdam C.S.
XIB - Bourg St Maurice
PAZ - Paris St Lazare
FRH - Calais Frethun
CAL - Calais Maritime
NNE - Narbonne
FNI - Nimes
CHV - Charleville Meziers
CMC - Chamberry Challes Les Eau
CTE - Chatelherault
OOS - Oostende
FRA - Frankfurt hbf
BOX - Bordeaux st jean
POI - Poiters
LIL - Lille flandres

**Comment by davwheat** [comment]
Find them in the audio files and sure 😛

https://github.com/Rail-Announcements/ketech-llpa-announcements/blob/main/Male1_transcriptions.csv

https://github.com/Rail-Announcements/ketech-llpa-announcements/blob/main/Female1_transcriptions.csv

**Comment by Boalbads** [comment]
well i found 2:
8321, MCK - disneyland/Marne-la-Vallé
866, ROT - rotterdam

**Comment by davwheat** [comment]
I already implemented both of these with Paris and Amsterdam :)

![Screenshot_20240126-212649](https://github.com/davwheat/rail-announcements/assets/7406822/eaf19cf1-3121-4a86-a308-d247a3b11b55)
![Screenshot_20240126-212642](https://github.com/davwheat/rail-announcements/assets/7406822/1c0fc152-7ce8-4cd7-97c7-36cf80d854d2)

**Comment by Boalbads** [comment]
oh didnt see rot, thanks!

**Comment by davwheat** [comment]
no worries!
