### ISSUE TITLE
"Use legacy TOC names" misaligned

### ISSUE THREAD

**Issue by Boalbads** [davwheat/rail-announcements#121]
![image](https://github.com/davwheat/rail-announcements/assets/68003904/18cfce63-6837-486f-b1e4-b57e651b1d3c)
As you can see, the switch is offset to the left slightly compared to the other buttons. I don't think this is intentional but I just randomly noticed it.

**Comment by davwheat** [comment]
This is intentional as the indented checkboxes are part of a group of settings with the label at the top. It's done for visual separation.
