### ISSUE TITLE
Amey platform alterations

### ISSUE THREAD

**Issue by davwheat** [davwheat/rail-announcements#122]

**Comment by davwheat** [comment]
> Attention please. This is a platform alteration. The xx:xx toc service from this station to destination, originally due to depart from platform x, will now depart from platform x. Platform x for the xx:xx toc service to destination.

**Comment by 313rail** [comment]
[plat alt.zip](https://github.com/davwheat/rail-announcements/files/14270771/plat.alt.zip)
Some examples can be heard here.

**Comment by davwheat** [comment]
Southern/SWT version is likely what I will model here:

> Attention please. This is a platform alteration. The xx:xx <toc> service to destination will now depart from platform x. Platform x for the xx:xx <toc> service to destination [...].

Example audio:
https://u.davwheat.dev/PtQURYxl.mpga
https://u.davwheat.dev/TbVkiNlx.mpga
