### ISSUE TITLE
Add more announcements 

### ISSUE THREAD

**Issue by opott** [davwheat/rail-announcements#123]
Multiple announcements have been released under FOI that are not yet on the website. These include:
- TPE Onboard
- London Overground/Elizabeth Line Station
- Bakerloo Line Onboard
- Central Line Onboard
And many more.

it would be nice for these to be on the website!

**Comment by davwheat** [comment]
Please split these into separate issues to be tracked individually

**Comment by GTRspotter** [comment]
Adding all of these files to the website is a lot of work. Currently, the focus is on adding files for the Merseyrail Class 777. I have personally collected station files for the London Overground/Elizabeth Line which are in Adobe format. However, converting them to MP3 or WAV would require a considerable amount of effort. Additionally, the files would need to be renamed to match the announcements. This process would also take a significant amount of time.

**Comment by opott** [comment]
> Please split these into separate issues to be tracked individually

@davwheat Will do! If I knew how to add the announcements to the repo myself I would do it. I’ll try to figure it out!

**Comment by GTRspotter** [comment]
> > Please split these into separate issues to be tracked individually
> 
> @davwheat Will do! If I knew how to add the announcements to the repo myself I would do it. I’ll try to figure it out!

@davwheat Could you guide me on adding TPE and London Overground/Elizabeth line station announcement files to this repo? I have the files.

**Comment by GTRspotter** [comment]
> > Please split these into separate issues to be tracked individually
> 
> @davwheat Will do! If I knew how to add the announcements to the repo myself I would do it. I’ll try to figure it out!

@davwheatCan you guide me through adding the TPE files and LO/Liz line files to this repository? I already have the files.

**Comment by GTRspotter** [comment]
> Please split these into separate issues to be tracked individually

I will do it now, they haven't done so.

**Comment by GTRspotter** [comment]
> Multiple announcements have been released under FOI that are not yet on the website. These include:
> 
> * TPE Onboard
> * London Overground/Elizabeth Line Station
> * Bakerloo Line Onboard
> * Central Line Onboard
>   And many more.
> 
> it would be nice for these to be on the website!

@opott What are these others? I will also create issues for these.
