### ISSUE TITLE
Hide "Edit board" on live announcements

### ISSUE THREAD

**Issue by GTRspotter** [davwheat/rail-announcements#124]
On the live trains board, you have the option to "Edit board". When you click this it brings you to the dot matrix home screen.

**Comment by 313rail** [comment]
That's because the board is on a website.

**Comment by davwheat** [comment]
But still worth fixing

**Comment by GTRspotter** [comment]
> That's because the board is on a website.

Although the board is from dot matrix, the dot matrix home screen should be removed from the Live Trains board.

**Comment by GTRspotter** [comment]
It would be better to remove the "edit board" button from the rail announcements website because to edit the board, you need to either exit full screen or scroll up.
