### ISSUE TITLE
[Live Trains] Issue with Legacy TOCs & WMT-style Board

### ISSUE THREAD

**Issue by opott** [davwheat/rail-announcements#130]
When using Live Trains with the WMT-style departure board, the use legacy TOCs does not take effect.

**Comment by opott** [comment]
> ![image](https://private-user-images.githubusercontent.com/140901151/304882189-a0f245d9-d88a-4071-b7f4-2080b5865d93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5NDY4NTYsIm5iZiI6MTcwNzk0NjU1NiwicGF0aCI6Ii8xNDA5MDExNTEvMzA0ODgyMTg5LWEwZjI0NWQ5LWQ4OGEtNDA3MS1iN2Y0LTIwODBiNTg2NWQ5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNFQyMTM1NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjJkNGQ5NWU0ZjUwZDIyM2FmY2RmZDI3ODZkZGFjMDM4ZjRjZjAzOWI2NDFmMWZmYTMxMjlhOTZjNzllYzJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dkU8ArlGO-hWaJ0wDa8UxWjrbu4KNegpM58256v_seA) ![image](https://private-user-images.githubusercontent.com/140901151/304882339-6835bbe9-d53a-415f-beeb-b8d2f31426f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5NDY4NTYsIm5iZiI6MTcwNzk0NjU1NiwicGF0aCI6Ii8xNDA5MDExNTEvMzA0ODgyMzM5LTY4MzViYmU5LWQ1M2EtNDE1Zi1iZWViLWI4ZDJmMzE0MjZmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNFQyMTM1NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZjVkNDc0ZmFmNGFjMTIzMWVlM2ZmNjRjY2E2ZTRmOWM1MGZhNjE5Y2VkNTEzYmJlMzQ0OWViOTFhZDRmZTExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BHdye0BzLeZEbBTTWjOLKFITtu997JYBwBjve53Os04) "Thameslink" should be First Capital Connect

Yep! I noticed it with West Midlands Railway, which should show as London Midland.

**Comment by davwheat** [comment]
![image](https://github.com/davwheat/rail-announcements/assets/7406822/67f8b2af-c5ad-43df-9375-8e29f38519c0)
