### ISSUE TITLE
[Amey Celia] Bodged West Midlands Trains TOC Announcement

### ISSUE THREAD

**Issue by opott** [davwheat/rail-announcements#133]
I have managed to create a bodged West Midlands Trains TOC snippet for Amey Celia. GitHub will not let me attach them to this issue, so they can be found in [this repository](https://github.com/opott/bodged-wmt).

**Comment by davwheat** [comment]
Thanks, but what would really be needed is West Midlands Railway and London Northwestern Railway rather than a generic WMT snippet.

**Comment by opott** [comment]
Will try and get that done!

**Comment by opott** [comment]
@davwheat 
Done the WMR and LNR ones. May not be the best quality, but maybe someone could enhance them in the future or make a better version? They are in [this repository](https://github.com/opott/bodged-wmt).
