### ISSUE TITLE
[Phil/Celia] Some 'via XXX' announcements can't be played

### ISSUE THREAD

**Issue by LK70AZR** [davwheat/rail-announcements#135]
Some via annoucements for Phil and Celia couldn't by played, for example "via Epsom" and "via Four Oaks"
"via University", and "via Cobham" announcements were able to play for some reason.
![Screenshot_20240216_201228_Chrome](https://github.com/davwheat/rail-announcements/assets/127895419/54e51ea9-34ca-4a53-b4f1-3fd457a7b00e)

**Comment by davwheat** [comment]
Regression after #120
