### ISSUE TITLE
[Amey Phil/Celia] Platform alternation announcement failed to play

### ISSUE THREAD

**Issue by LK70AZR** [davwheat/rail-announcements#138]
388200846f0b4e749807cbfa16310595(Phil)
57223737795e4fe1b1e7a5ca88804320(Celia)

Please fix as soon as you can, thanks

**Comment by GTRspotter** [comment]
Did you forget to post the announcement on a new platform? I have experienced this.

**Comment by davwheat** [comment]
"urgent"
"fix asap"

Don't be so entitled, please.

**Comment by LK70AZR** [comment]
> Did you forget to put a new platform? I have experienced this.

Oh nvm I just clicked a random present and play it lol.

> "urgent" "fix asap"
> 
> Don't be so entitled, please.
Apologises 🙇‍♂️
