### ISSUE TITLE
Unable to select xx:01 times on station announcements

### ISSUE THREAD

**Issue by p-evans** [davwheat/rail-announcements#145]
The drop down option gives 00 - hundred, 00 - hundred-hours, 02, 03, 04, [...], 58, 59

![image](https://github.com/davwheat/rail-announcements/assets/54455836/04925fb2-6ca1-4964-9ffc-4d6a587a6320)

This prevents being able to announce the "Oh one oh one one service from platform one"

**Comment by davwheat** [comment]
Hah, yeah that's definitely an issue!
