### ISSUE TITLE
[Amey Phil & Celia] Bodged East Midlands Railway files.

### ISSUE THREAD

**Issue by faberoony90** [davwheat/rail-announcements#151]
I have edited together a bodged set of East Midlands Railway TOC files, they can be found here: https://github.com/faberoony90/Bodged-EMR

This includes the "to/from" announcements by each Phil and Celia, and the singular TOC with both inflictions.
If someone else can provide better samples then those should be used instead.

**Comment by davwheat** [comment]
[Bodged-EMR-main.zip](https://github.com/davwheat/rail-announcements/files/14546245/Bodged-EMR-main.zip)

**Comment by davwheat** [comment]
https://u.davwheat.dev/beMMhoVa.mpga
