### ISSUE TITLE
Daktronics fanfare

### ISSUE THREAD

**Issue by GTRspotter** [davwheat/rail-announcements#169]
When the "No chime" option is selected and the "Play Daktronics fanfare" is selected, the fanfare doesn't play at all. I have to select a chime for the fanfare to play.
![image](https://github.com/davwheat/rail-announcements/assets/140901151/3b1f7727-0365-4105-8478-d999de95f903)

**Comment by 313rail** [comment]
Was gonna report the same thing - beat me to it

**Comment by opott** [comment]
I'm experiencing this too!
