### ISSUE TITLE
At some stations, the board is broken.

### ISSUE THREAD

**Issue by TrainGuide** [davwheat/rail-announcements#174]
For example at KGX station, I can hear the announcements but I cant see the departure board

**Comment by davwheat** [comment]
Ah, this will be because KGX always hide platforms to 3rd party data tools rather than confirming them like normal stations do. It's extremely frustrating, but a data limitation. What I can do is add an option to show services on the board with no confirmed platform.

**Comment by TrainGuide** [comment]
Thanks!
