### ISSUE TITLE
Add proper names instead of "Unknown Name"

### ISSUE THREAD

**Issue by davwheat** [davwheat/rail-announcements#184]
Also add additional options for other locations.

**Comment by CarolStott** [comment]
I was going to open this issue, but I'm glad that you're on top of this. May I ask how things are going re the unknown stations? If it helps, I have compiled a spreadsheet of the unknowns, and did my best to find what the announcements refer to. However, I did run in to a few issues along the way, such as why Phil Sayer did Peel (presumably the one on the Isle of Man) or Stranraer West Pier. 

Thank you for this amazing tool, best of luck with your other projects.
Below is the spreadsheet. Hope it helps :)
[Phil Sayer's Unknown Stations.xlsx](https://github.com/davwheat/rail-announcements/files/15250797/Phil.Sayer.s.Unknown.Stations.xlsx)

Regards,
Caroline
