### ISSUE TITLE
C2c operator not listed

### ISSUE THREAD

**Issue by Chazzagxox** [davwheat/rail-announcements#19]
Following rail operators not listed on system as of yet [ATOS ANNE] 
c2c
TfW instead of Arriva
South Western Railway
Great Western Railway 
Greater Anglia 

following stations not yet added  [ATOS ANNE] 
Looe [Cornwall] 
Castle Cary
St Ives [Cornwall]
Diss [Norfolk]

**Comment by davwheat** [comment]
This is a limitation of the real world announcements set I have access to.
