### ISSUE TITLE
Allow user to set amount of chimes in live announcements

### ISSUE THREAD

**Issue by Boalbads** [davwheat/rail-announcements#190]
for the live announcements, it would be nice if there was a dropdown to select the amount of chimes (for each announcer/all in general?), e.g. I personally prefer 3 chimes rather than 4, but when I select Phil, I hear 4 chimes with no way to change it.

**Comment by polskism** [comment]
because in real life on the system this is based off of, 3 chimes were played for celia announcements and 4 for phil

**Comment by Boalbads** [comment]
but I have seen both Celia and Phil play without any chimes sometimes.

**Comment by polskism** [comment]
because thats on a different system
