### ISSUE TITLE
[Class 700/707/717] SPL files

### ISSUE THREAD

**Issue by GTRspotter** [davwheat/rail-announcements#193]
It bothers me when the announcement says "London St Pancras" instead of "London St Pancras International". It really doesn't sound right when you go on Thameslink trains a lot.

**Comment by 313rail** [comment]
Brought this up ages ago

**Comment by GTRspotter** [comment]
Where?

**Comment by 313rail** [comment]
https://github.com/davwheat/rail-announcements/issues/80

**Comment by davwheat** [comment]
Ah I thought that ticket was about the live trains rather than on board. I didn't see your follow-up comment at the end.
