### ISSUE TITLE
Question about running this as a kiosk page?

### ISSUE THREAD

**Issue by ghollingworth** [davwheat/rail-announcements#199]
Hi,

Was wondering whether it would be possible to have this installed onto a Raspberry Pi (in an apache server for example) so that it would just run automatically with a specific station?

Have an autistic family member who loves to listen (land memorise) train announcements and was thinking this would be a great birthday present!

Gordon

**Comment by davwheat** [comment]
The dot matrix is available in a kiosk mode, but I hadn't considered that for the live announcements too!

I could do something similar to that for the announcements too.

**Comment by ghollingworth** [comment]
I was thinking of just using FullPageOS, but serve it locally...

https://github.com/guysoft/FullPageOS

**Comment by davwheat** [comment]
You'd need to build the site, as well as add in new functionality to parse configuration options from the query params or something similar. This is probably less work than an `onload` JS payload which fills out the options automatically.

`yarn build` should be sufficient to build the site, which will dump HTML, JS and CSS into `public/`. It'll need internet to fetch the audio files from the storage bucket and to hit my Darwin API.

It's worth considering automating updates to the implementation as audio files can be renamed as needed, and to ensure that bug fixes and new functionality reaches the kiosk implementation.

In addition, I may move away from my current Darwin API implementation (as I'm reaching RDG's free use limits) and instead implement my own push port service for the Darwin feed. I don't plan to shut down my REST API as other things use it, though.
