### ISSUE TITLE
static/audio/SN/377/stations/PMS.mp3 incorrectly says "Bognor Regis"

### ISSUE THREAD

**Issue by seawolf** [davwheat/rail-announcements#20]
https://github.com/davwheat/rail-announcements/blob/main/static/audio/SN/377/stations/PMS.mp3

**Comment by seawolf** [comment]
This 404s now...?

**Comment by davwheat** [comment]
Yes, I removed this when I got some better recordings from elsewhere. Sorry for not updating the issue.

**Comment by seawolf** [comment]
I think selecting PMS for any of the announcements breaks something, but that's a separate thing 😉
