### ISSUE TITLE
[Amey Phil / Celia] Avanti West Coast (Pendolino / Voyager / Evero) TOC sound files

### ISSUE THREAD

**Issue by LX9702** [davwheat/rail-announcements#216]
Quite self-explanatory but what is included in the file:
Avanti West Coast 
Avanti West Coast Pendolino
Avanti West Coast Voyager
Avanti West Coast service to
Avanti West Coast Pendolino service to
Avanti West Coast Voyager service to

How it's created (sort of)
N**av**igation Road, **Fa**rnworth, twen**ty**, South **Wes**t Trains, National Express Eas**t Coast**

[avanti west coast.zip](https://github.com/davwheat/rail-announcements/files/15420214/avanti.west.coast.zip)

**Comment by opott** [comment]
Nice work! I'd been trying to think of a way to create the sound files for Avanti for ages 😂

**Comment by LX9702** [comment]
Hi guys! I am back with some updates with the files.
Just in case that announcing AWC Evero is available, I also made an AWC Evero for it. 
The zip file below only contains Avanti West Coast Evero version only, so when implementing, please do also download [this](https://github.com/davwheat/rail-announcements/files/15420214/avanti.west.coast.zip).

[evero.zip](https://github.com/user-attachments/files/15793307/evero.zip)

**Comment by LX9702** [comment]
(Also I am aware of the fact that there are no "service to" variation, it is because that I uh... can't be bothered to do so + we can add "service to" after "AWC Evero".
