### ISSUE TITLE
[Amey Phil Celia] Onboard facilities files

### ISSUE THREAD

**Issue by tdubbs1** [davwheat/rail-announcements#220]
A selection of onboard facilities announcements for Phil/Celia (trolley service, buffet, WiFi, travelling chef etc). For some of the messages (e.g. "trolley service" and "at-seat service"), I conjoined multiple recordings together in a DAW in order to get the most accurate representation of how the audio was played in real life.

Would be great to see them uploaded onto the generator (not sure if it's applicable to Live due to data feed constraints).

[[AMEY PHIL CELIA] Onboard facilities.zip](https://github.com/davwheat/rail-announcements/files/15445495/AMEY.PHIL.CELIA.Onboard.facilities.zip)

**Comment by davwheat** [comment]
I'd need to ingest the timetable data for this rather than solely using the live data from Darwin.

**Comment by davwheat** [comment]
WIP: https://github.com/davwheat/timetable-ingester/

**Comment by davwheat** [comment]
On second thought, I'll still close this as a duplicate given that the features should come to live trains and the generator at the same time.
