### ISSUE TITLE
Audio stutters, especially when using wireless audio devices

### ISSUE THREAD

**Issue by davwheat** [davwheat/rail-announcements#221]
Wireless audio devices don't seem to like it when the website suddenly starts playing audio, and they stutter trying to "catch up" to what they should actually be playing after the start of an announcement.

We might want to add 0.5s/1s of silence to the start of every announcement to mitigate this.

**Comment by p-evans** [comment]
I had it recently playing out of my phone directly - some announcements were ok, the others sounded like they had that carrier bag plastic stretched semi-taut over fan blades sound effect going on.

It actually added to the ambience of early privatisation, where the old ex-NSE kit that hadn't been invested in for years was trying valiantly to do its job.

Chrome, Pixel 7 Pro

**Comment by davwheat** [comment]
This seems rather infeasible to fix, as you'd just cause issues for some people when trying to resolve issues for others.
