### ISSUE TITLE
[Live Trains] Whitlocks End via Whitlocks End

### ISSUE THREAD

**Issue by opott** [davwheat/rail-announcements#231]
When using Live Trains at Birmingham Moor Street, services to Whitlocks End are announced and displayed as Whitlocks End via Whitlocks End.

![image](https://github.com/davwheat/rail-announcements/assets/120502505/9b6a8d9a-60f4-4fcf-8c86-80c488bf4c86)

**Comment by davwheat** [comment]
This is a limitation of the Darwin data feed caused by WMT inputting garbage.

The announcement system can only be as good as what the operators provide, unfortunately.
