### ISSUE TITLE
error while playing an announcement

### ISSUE THREAD

**Issue by hhsquidward** [davwheat/rail-announcements#236]
i tried playing an announcement for an all stations woking - weymouth service using celia's voice announcements and got given error ID 8aa53fd5feb143b882fa968c2d56047b instead of the announcement playing

error info:
EncodingError: Failed to execute 'decodeAudioData' on 'BaseAudioContext': Unable to decode audio data
Error: Failed to execute 'decodeAudioData' on 'BaseAudioContext': Unable to decode audio data

**Comment by davwheat** [comment]
Could you share a link to the announcement you tried to play?

**Comment by hhsquidward** [comment]
unfortunately the device which i have it on i currently cannot access. i should be able to on wednesday.

**Comment by hhsquidward** [comment]
Sorry for the extremely long wait, something out of hand happened and only now was I able to access the announcement
here is the shared announcement link: https://railannouncements.co.uk/stations/amey-celia-drummond/?announcementId=ad81769b-dd5b-431c-91bb-b45618fdf309

**Comment by davwheat** [comment]
You're missing a first class location (this was likely added after you saved this preset) which is what is causing the error.

**Comment by hhsquidward** [comment]
Setting the first class location fixes the problem. Thanks.
