### ISSUE TITLE
RRB Ends - does not play on last calling point

### ISSUE THREAD

**Issue by p-evans** [davwheat/rail-announcements#240]
I saw the new feature on Phil and had a fiddle. An RRB announcement is missed when the RRB ends at the final intermediate station

Repro steps
Create an announcement for a service to Brighton
Add calling points of Havant, Chichester, Worthing

Set the train to end at Havant and resume at Chichester
Expected: Announcement plays indicating the train will stop at Havant and resume at Chichester
Actual: Announcement plays indicating the train will stop at Havant and resume at Chichester

Set the train to end at Havant and resume at Worthing
Expected: Announcement plays indicating the train will stop at Havant and resume at Worthing
Actual: Announcement plays indicating the train will stop at Havant and be a bus all the way to Brighton

**Comment by davwheat** [comment]
Reproduction link: https://railannouncements.co.uk/stations/amey-phil-sayer/?announcementId=1d991956-2b8a-4566-9736-a1e7a7a8fab3
