### ISSUE TITLE
[Phil/Celia] Delay announcements on 120 minutes OR above are not playable

### ISSUE THREAD

**Issue by LK70AZR** [davwheat/rail-announcements#242]
As title

Error reference:
655c2ca601974e1681059b508473411c - Celia
c5978d0737bd4e17942ac2e6a04b6bb9 - Phil

**Comment by Boalbads** [comment]
They are actually, just some (eg 360 minutes) do not work.

**Comment by davwheat** [comment]
Probably a bug with my code which converts from minutes to hours and minutes lol
