### ISSUE TITLE
[Live Trains] Short platform info is wrong after an enroute formation change

### ISSUE THREAD

**Issue by GTRspotter** [davwheat/rail-announcements#245]
When Phil Sayer was announcing a Southern service to Caterham and Tattenham Corner, which is formed of 10 coaches. After the train divided at Purley, where both formations have 5 coaches. It then announced the short platforms at Kenley and Whyteleafe South saying "Customers for Kenley should board the front 7 coaches". The train has 5 coaches by the time it has reached Kenley.

**Comment by faberoony90** [comment]
That's not the only example. I think currently, all splits & shorts, 'fight' each other, and the short platform piece comes in regardless. But additionally there's some that aren't listed the correct way prior to reversal (any Victoria - Eastbourne are claimed as front XXX for stops beyond Eastbourne, where these would only be the front after Eastbourne, and rear prior)

**Comment by davwheat** [comment]
In reality, the system shouldn't even announce short platforms after a service divides.

This should have been implemented as part of 2977af30875aa98a61f7caa28c1091fe1b4866c0 but it doesn't seem to work properly.

**Comment by davwheat** [comment]
This should now have been _properly_ fixed
