### ISSUE TITLE
London Waterloo International not selectable 

### ISSUE THREAD

**Issue by Boalbads** [davwheat/rail-announcements#248]
I can see the sound is there, however it is not selectable (station code is WIT if you needed it)![Screenshot_20240703-171619.png](https://github.com/davwheat/rail-announcements/assets/68003904/07d7eb17-5d90-41f5-ad0c-29a85303f2a6)

**Comment by davwheat** [comment]
London Waterloo International does not exist anymore.

This would be covered by #184

**Comment by Boalbads** [comment]
It'd be nice to have it, even if it is not selectable, simply because the announcement exists and some people would like to make some... truly insane announcements. Weymouth quay is unable to have trains anymore, yet it still is selectable.
