### ISSUE TITLE
Announcement for trains dividing.

### ISSUE THREAD

**Issue by Rushaune157** [davwheat/rail-announcements#252]
Not sure if it's already been flagged but lately starting to hear for example the Bognor and Portsmouth trains which divide at Horsham then Announcing it's not stopping at Horsham

**Comment by davwheat** [comment]
This should have been fixed yesterday. Was it happening today?

**Comment by davwheat** [comment]
Ah, the repetition of all the stops was fixed but the addition of the divide points wasn't. Thanks, I'll look into this.
