### ISSUE TITLE
Thanet Parkway (THP)

### ISSUE THREAD

**Issue by Bushey72** [davwheat/rail-announcements#263]
Thanet Parkway is not being announced.

**Comment by LX9702** [comment]
Because there are no audio snippet for that station.
![image](https://github.com/user-attachments/assets/e701f09a-d7d9-4522-8d87-c84743fbe65a)
![image](https://github.com/user-attachments/assets/ebb37ee3-d95d-4016-965e-411e86efb5cb)

**Comment by GTRspotter** [comment]
This station was only made a year ago, and Phil stopped recording in 2016.

**Comment by davwheat** [comment]
I think we can more bluntly say that he died in 2016.

**Comment by GTRspotter** [comment]
Can this issue not be closed?

**Comment by Bushey72** [comment]
Yes.  I am sure the sound file will come along in due course.

**Comment by davwheat** [comment]
> Can this issue not be closed?

Always possible to bodge recordings from other stations!

**Comment by GTRspotter** [comment]
It would be difficult as there is no "Thanet." Additionally, even if we were to create "Thanet," it probably wouldn't be an appealing announcement.
