### ISSUE TITLE
Julie Berry says Waterloo (Merseyside) as Woolwich Arsenal (+suggestion)

### ISSUE THREAD

**Issue by privatedev11** [davwheat/rail-announcements#31]
This video shows this bug, where Julie Berry says Waterloo (Merseyside) as Woolwich Arsenal.
https://youtu.be/N5Qr_6mZtoE

Also on the topic of Julie Berry, they do the announcements on Merseyrail, so that could be a new announcer. There are some differences between the announcements on the Class 507/8s and the new 777s, but they are only minor, like new 'this is' announcements etc. See these videos for info (not mine):
Class 777: https://www.youtube.com/watch?v=kiion1dZBT8
Class 507/8: https://www.youtube.com/watch?v=Eps84A0W_9o&t=0s

**Comment by davwheat** [comment]
Fix for this deploying in the next 15 mins.
