### ISSUE TITLE
LNER Azuma Announcements

### ISSUE THREAD

**Issue by GTRspotter** [davwheat/rail-announcements#36]

**Comment by davwheat** [comment]
LNER Azuma announcements here. This includes: All stations, Cut List, Letters and Numbers (Male announcer).

sharedrop-2023-09-29-17_00_05.zip
sharedrop-2023-09-29-16_59_39.zip
sharedrop-2023-09-29-16_59_14.zip
sharedrop-2023-09-29-16_58_40.zip
sharedrop-2023-09-29-16_58_16.zip
