### ISSUE TITLE
All Phil Sayer Announcement are not able to play with the usual error message

### ISSUE THREAD

**Issue by LK70AZR** [davwheat/rail-announcements#41]
As per title

For reference:
ba1563834ee74e5784ae0d675bcf5861
6b87f0631dcf42bf8e6cca31c733613e

**Comment by LK70AZR** [comment]
Update: seems 'hundred-hour' announcements not able to play now
6a68ef4cfeca47bfa50b918f16715ac7

**Comment by LK70AZR** [comment]
The spilting announcement is not working as of the latest update

b5cefaae2f2a4cbab5551f7909ecf39d
69aca91db430487cb5c9af9c46d0849c

**Comment by davwheat** [comment]
I cannot reproduce the issue @LK70AZR

Please open a new issue if this is still a problem
