### ISSUE TITLE
Phil Sayer for serveral downwards voice 

### ISSUE THREAD

**Issue by LK70AZR** [davwheat/rail-announcements#45]
Newcrainghall played as Newport(Wales)
Newhaven Harbour played as Newhaven Town
Newhaven Town played as Norbury
Norbury and Newcastle voice are not able to play with error message

For reference:
Norbury
e80164b2250f4bbb90f6825315f93cc4
Newcastle
6eca8ca2aef140b5881311d8222e8c27

**Comment by davwheat** [comment]
Thanks for this. They're all transcription errors and will be fixed in https://github.com/Rail-Announcements/ketech-llpa-announcements and ported over here.

**Comment by davwheat** [comment]
Should be fixed now
