### ISSUE TITLE
Phil Hampton Wick and West Ham

### ISSUE THREAD

**Issue by LK70AZR** [davwheat/rail-announcements#52]
Would you be able to double check your Phil sound file to see if these two files exist on that, as Hampton Wick is a SWR station and both of them are obviously existed for a long time

**Comment by davwheat** [comment]
This was an issue from the transcriptions. One of the Hampton Wick files was incorrectly transcribed as Hampton, meaning it wasn't included in the list of supported stations. This will be fixed soon.

**Comment by davwheat** [comment]
Similarly, West Ham didn't have its CRS code transcribed.

**Comment by davwheat** [comment]
Fixed
