### ISSUE TITLE
Calling at station screen does not scroll bugs out 

### ISSUE THREAD

**Issue by zak0905** [davwheat/rail-announcements#56]
The calling at station bit is buggy does not load only shows incident information and carriage info

**Comment by davwheat** [comment]
I need far more information than this.

What calling point info? Where? Screenshot? When does this happen? What device and browser do you use? What station have you picked?

**Comment by zak0905** [comment]
[
![89AC67F7-AB15-40F8-B159-775C1CE8E580](https://github.com/davwheat/rail-announcements/assets/151881322/af86a7bf-44b0-4847-a4b0-a56de9d73ae1)
![DD716FA3-C0DB-401D-B0E4-69D4F7CC81CA](https://github.com/davwheat/rail-announcements/assets/151881322/d7a9cae7-e347-464c-80f2-46a7134edcc6)
](url)###  it would literally just stop like that and pause am on safari checked on chrome too

**Comment by davwheat** [comment]
For the record, on iOS all browsers use Safari.

The dot matrix board is rather broken generally and has many issues. I plan to rewrite it fully in the future to (hopefully) fix most of these issues.

I can't reproduce this specific issue on any of my devices, and I don't own an iOS device to test on.

I've attached about 5m 30s of running the dot matrix below.

https://github.com/davwheat/rail-announcements/assets/7406822/2f17b485-8da7-4679-b685-a7a38b1621cf

**Comment by zak0905** [comment]
Thank you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
