### ISSUE TITLE
Live Announcements Beta

### ISSUE THREAD

**Issue by TomCripps** [davwheat/rail-announcements#62]
Live display has become unavailable with Live announcements, certain stations get stuck on 'still announcing service' when announcement finished a minute ago. Also other voices are available - TFW Ruth 175, Merseyrail Julie 777, Michael Comyn IÉ stations (same pack as DITRA), ScotRail stations newer announcement voice, London Overground onboard and stations Emma Hignett. These are publicly available now and I think we'd all love to see them uploaded. Keep up the excellent work, it's my new favourite website

**Comment by davwheat** [comment]
> Live display has become unavailable with Live announcements
Should be fixed
> certain stations get stuck on 'still announcing service' when announcement finished a minute ago
This can happen if you leave the tab in the background.

It can also happen while it's trying to download files for the next announcement. Sometimes this takes a while due to browser limits and other schenanigans.

**Comment by privatedev11** [comment]
> Merseyrail Julie 777

Check out issue #32
