### ISSUE TITLE
Celia platform A and B

### ISSUE THREAD

**Issue by LK70AZR** [davwheat/rail-announcements#66]
Celia's platform A and B announcement are not working, here is the error codes:

939cb3192ca64b5d98fcc04ecc98b01e(Plat A)
ef1449e6b7f34f24855e1162b9d98c65(Plat B)

**Comment by GTRspotter** [comment]
I have the same thing
Error codes:
Plat A - 01450fa696a44d85b1c2c8033a0ca3ee
Plat B - 5a200d53c587433cb4ec4b17d15da577
