### ISSUE TITLE
Azuma route start/departing station announcement

### ISSUE THREAD

**Issue by GTRspotter** [davwheat/rail-announcements#73]
Thank you for adding this, this is my favourite system so far. Do you think you're planning on making a start of route/station departure for the system? I think it would be more realistic.

**Comment by davwheat** [comment]
Find me some videos, and sure!

**Comment by GTRspotter** [comment]
A video here. LNER Azuma on departure.
https://youtu.be/EgDFN4eAIaY?feature=shared

**Comment by GTRspotter** [comment]
I found some vids
