### ISSUE TITLE
[Live Trains] Allow a combination of Phil/Celia per-platform

### ISSUE THREAD

**Issue by davwheat** [davwheat/rail-announcements#75]
Most stations (near me) used Phil and Celia for up/down AM and down/up PM respectively, so it'd be nice if we can configure a combination of both for a given station.

**Comment by GTRspotter** [comment]
Would this mean having a combined Live Trains system?

**Comment by davwheat** [comment]
Well, yes

**Comment by GTRspotter** [comment]
Would that be a new system or under Phil or Celia? I am assuming a new system called "Amey/Ditra Phil Sayer/Celia Drummond Live Trains"

**Comment by davwheat** [comment]
No idea yet

**Comment by GTRspotter** [comment]
I also think that we should still have an option to do just Phil or just Celia, and make a new system for both.

**Comment by davwheat** [comment]
I mean yes, it's a new feature, not removal of existing functionality.

**Comment by GTRspotter** [comment]
How would Phil and Celia be combined? By Northbound and Southbound, for example.
