### ISSUE TITLE
Using wrong files for 'London St Pancras' on Thameslink Core

### ISSUE THREAD

**Issue by 313rail** [davwheat/rail-announcements#80]
On the class 700 in real life London St Pancras on the Thameslink core uses the recording 'London St Pancras International' and uses the CRS code 'SPL'  instead of what you are using at the moment which is the high level platforms saying just 'london st Pancras' which uses CRS code 'STP'

**Comment by davwheat** [comment]
The GTR and Southeastern CIS's announce St Pancras Low Level/High Speed as "London St Pancras International" in real life.

The EMR CIS announces St Pan High Level as "London St Pancras" in real life.

The system is simply attempting to model different systems as well as possible.

https://github.com/davwheat/rail-announcements/blob/bd7ac660fd46e7083fb41baa8905a51187e743ff/src/announcement-data/systems/stations/AmeyPhil.tsx#L3443-L3450

**Comment by 313rail** [comment]
Fair enough

**Comment by GTRspotter** [comment]
Shouldn't there be an option to choose whether you want the GTR 'London St Pancras International' or the EMR 'London St Pancras'.

**Comment by davwheat** [comment]
Quite honestly, that's a big chunk of work to implement with how it's all set up at the moment, with rather little benefit.

**Comment by GTRspotter** [comment]
Just wondering, is the GTR 'London St Pancras International' audio file on this website? I would like to use this myself

**Comment by 313rail** [comment]
Can't you just add another button for it

**Comment by GTRspotter** [comment]
He said it's a big chunk of work for little benefit, which is fair enough.

**Comment by GTRspotter** [comment]
Does it really take a lot of work to add 1 file?

**Comment by davwheat** [comment]
It's not about adding the file. All the files available are there, and all the files are already used as I mentioned earlier, depending on whether it's High Speed, Midland or Thameslink platforms.

There is no London St Pancras Intl file in the audio, though, to answer your question, hence the use of St Pancras Intl instead.

![](https://github.com/davwheat/rail-announcements/assets/7406822/abc867a3-8017-4354-bd3c-0c44731ef5a1)

And I can't just "add another button for it", which is the main issue.

**Comment by GTRspotter** [comment]
I found the file for the TL St Pancras Intl.

**Comment by davwheat** [comment]
Because that's how many there are?

**Comment by GTRspotter** [comment]
Whats the inlfection?

**Comment by davwheat** [comment]
**s**tart/**m**iddle/**e**nd of a sentence

**Comment by GTRspotter** [comment]
oh ok

**Comment by 313rail** [comment]
I was referring to onboard the 700/707s. The files 
![Screenshot_20240102-170814](https://github.com/davwheat/rail-announcements/assets/145853789/72d088b9-7eca-43a4-b588-84e8ef78ecba)
does exist as STA_SPL and STB_SPL
