### ISSUE TITLE
Class 377 announcements - 

### ISSUE THREAD

**Issue by 313rail** [davwheat/rail-announcements#81]
Hi. Just tried to create an announcement and it's playing the wrong audio clips, I'm putting in "This station" as Preston Park and "Terminating station" as brighton and the announcement that is playing is the terminating at Preston Park announcement.

**Comment by 313rail** [comment]
https://railannouncements.co.uk/?announcementId=28177896-c3f0-4be8-8a11-e525d34e55c8 what I did

**Comment by GTRspotter** [comment]
Same here, does the same with Angmering to Littlehampton.
https://railannouncements.co.uk/?announcementId=d5c9a5e2-6c57-4fb3-8870-a5a1ded5b853

**Comment by 313rail** [comment]
So basically any of the ones with crap recordings

**Comment by GTRspotter** [comment]
No, it is just when there is no calling points.

**Comment by davwheat** [comment]
This is caused by something I changed last night. I'll fix it soon.
