### ISSUE TITLE
LNER Azuma

### ISSUE THREAD

**Issue by GTRspotter** [davwheat/rail-announcements#85]
There is no "Change here for trains to" on the system

**Comment by davwheat** [comment]
Tell me where they need to be and I'll add them.

**Comment by GTRspotter** [comment]
https://www.youtube.com/watch?v=_5NByDkLIsQ
A video here for an example. When you say 'Tell me where they need to be' do you want me to tell you the change points for every station, or tell you where in the announcement.

**Comment by davwheat** [comment]
Preferably what it should be for each station. I have no idea. I imagine Tyne and Wear for Newcastle, and that's all I know.

**Comment by GTRspotter** [comment]
I don't know if they are on the audio files on this website. It might say this on the train.
Peterborough - Nottingham, Derby, Leicester, Bedford and Luton Airport.
Grantham - Skegness
Newark Northgate - Gainsborough Central
Doncaster - Preston, Hull, Cleethorpes
Leeds - Barrow-in-Furness, Bradford Interchange/Forster Square
York - Harrogate, Scarborough, Middlesbrough
Newcastle - Sunderland, Carlisle
Edinburgh Waverley - Glasgow Queen Street/Central, 
There is more but I have looked at the National Rail map PDF and couldn't see anything else.
https://assets.nationalrail.co.uk/e8xgegruud3g/5fzeEKhKFk5ms4Ip6wGpG1/3a9eb099cf65a34bc97f0103be07abbf/Rail_map_v38_orange_May_23.pdf

**Comment by GTRspotter** [comment]
If anyone else sees this and you know some of the change points, please tell us. Thank you.
