### ISSUE TITLE
TfW TranFX heart of wales announcement can't play properly

### ISSUE THREAD

**Issue by LK70AZR** [davwheat/rail-announcements#95]
Some station couldn't play properly on the heart of wales line(all station swansea-shrewsbury), not sure which one

77a062a8ad464130bf6c3afec3adc8ac

**Comment by LK70AZR** [comment]
Refer to issue #99 please

**Comment by davwheat** [comment]
I've told you before to stop making duplicates for the same issue. Don't do it again.
